export const KeywordNames = {
  Breakthrough: 'Breakthrough',
  Charge: 'Charge',
  Drain: 'Drain',
  Guard: 'Guard',
  Lethal: 'Lethal',
  Mobilize: 'Mobilize',
  Prophecy: 'Prophecy',
  Rally: 'Rally',
  Regenerate: 'Regenerate',
  Ward: 'Ward'
}

export const Mechanics = {
  Action: 'Action',
  Activate: 'Activate',
  Animal: 'Animal',
  'Another Creature': 'Another Creature',
  'Another Friendly Creature': 'Another Friendly Creature',
  Assemble: 'Assemble',
  Attack: 'Attack',
  Attribute: 'Attribute',
  Aura: 'Aura',
  Banish: 'Banish',
  Battle: 'Battle',
  'Beast Form': 'Beast Form',
  Betray: 'Betray',
  Buff: 'Buff',
  'Buff Hand': 'Buff Hand',
  'Buff Deck': 'Buff Deck',
  'Buff Race': 'Buff Race',
  'Burn Damage': 'Burn Damage',
  "Can't": "Can't",
  Change: 'Change',
  Choose: 'Choose',
  Consume: 'Consume',
  Copy: 'Copy',
  Cover: 'Cover',
  Cost: 'Cost',
  'Cost Reduction': 'Cost Reduction',
  'Cost Increase': 'Cost Increase',
  Creature: 'Creature',
  'Both Lanes': 'Both Lanes',
  Damage: 'Damage',
  'Damage Creature': 'Damage Creature',
  'Damage Opponent': 'Damage Opponent',
  Debuff: 'Debuff',
  Destroy: 'Destroy',
  'Destroy Creature': 'Destroy Creature',
  'Destroy Support': 'Destroy Support',
  Discard: 'Discard',
  Draw: 'Draw',
  Enemy: 'Enemy',
  'End of': 'End of',
  Empower: 'Empower',
  Equip: 'Equip',
  Exalt: 'Exalt',
  Expertise: 'Expertise',
  Friendly: 'Friendly',
  'Gain Health': 'Gain Health',
  'Gain Power': 'Gain Power',
  'Gain Magicka': 'Gain Magicka',
  'Gain Keyword': 'Gain Keyword',
  Give: 'Give',
  Heal: 'Heal',
  Health: 'Health',
  Ignore: 'Ignore',
  Immune: 'Immune',
  'Immune to Shackle': 'Immune to Shackle',
  'Immune to Lethal': 'Immune to Lethal',
  'Immune to Wounded': 'Immune to Wounded',
  'Immune to Damage': 'Immune to Damage',
  'Immune to Silence': 'Immune to Silence',
  'Immune to Target': 'Immune to Target',
  Invade: 'Invade',
  Lane: 'Lane',
  'Last Gasp': 'Last Gasp',
  Magicka: 'Magicka',
  Mono: 'Mono',
  Move: 'Move',
  Ping: 'Ping',
  Pilfer: 'Pilfer',
  Plot: 'Plot',
  Power: 'Power',
  'Put a': 'Put a',
  Random: 'Random',
  'Random Card': 'Random Card',
  'Random Creature': 'Random Creature',
  'Random Action': 'Random Action',
  'Random Item': 'Random Item',
  'Random Support': 'Random Support',
  Reduce: 'Reduce',
  Recursion: 'Recursion',
  Rune: 'Rune',
  Sacrifice: 'Sacrifice',
  Shackle: 'Shackle',
  Shuffle: 'Shuffle',
  Shout: 'Shout',
  Silence: 'Silence',
  Slay: 'Slay',
  Steal: 'Steal',
  'Start of': 'Start of',
  Summon: 'Summon',
  Transform: 'Transform',
  'Treasure Hunt': 'Treasure Hunt',
  Undead: 'Undead',
  Unique: 'Unique',
  Singleton: 'Singleton',
  Unsummon: 'Unsummon',
  Veteran: 'Veteran',
  'Wax and Wane': 'Wax and Wane',
  Wounded: 'Wounded',
  'Win the Game': 'Win the Game'
}

export const AttributeNames = {
  Strength: 'Strength',
  Willpower: 'Willpower',
  Intelligence: 'Intelligence',
  Agility: 'Agility',
  Endurance: 'Endurance',
  Neutral: 'Neutral'
}

export const DualColorClasses = {
  Battlemage: 'Battlemage',
  Crusader: 'Crusader',
  Archer: 'Archer',
  Warrior: 'Warrior',
  Mage: 'Mage',
  Assassin: 'Assassin',
  Sorcerer: 'Sorcerer',
  Monk: 'Monk',
  Spellsword: 'Spellsword',
  Scout: 'Scout'
}

export const TriColorHouses = {
  Guildsworn: 'Guildsworn',
  Dagoth: 'Dagoth',
  Daggerfall: 'Daggerfall',
  Hlaalu: 'Hlaalu',
  Redoran: 'Redoran',
  Ebonheart: 'Ebonheart',
  Dominion: 'Dominion',
  Tribunal: 'Tribunal',
  Telvanni: 'Telvanni',
  Empire: 'Empire'
}

export const Classes = {
  ...AttributeNames,
  ...DualColorClasses,
  ...TriColorHouses
}

export const ExpansionSets = {
  CoreSet: 'Core Set',
  ForgottenHeroCollection: 'Forgotten Hero Collection',
  FallOfTheDarkBrotherhood: 'The Fall of the Dark Brotherhood',
  ReturnToClockworkCity: 'Return to Clockwork City',
  HeroesOfSkyrim: 'Heroes of Skyrim',
  MadhouseCollection: 'Madhouse Collection',
  HousesOfMorrowind: 'Houses of Morrowind',
  FrostSparkCollection: 'FrostSpark Collection',
  IsleOfMadness: 'Isle of Madness',
  AllianceWar: 'Alliance War',
  MoonsOfElsweyr: 'Moons of Elsweyr',
  JawsOfOblivion: 'Jaws of Oblivion',
  TamrielCollection: 'Tamriel Collection',
  MonthlyReward: 'Monthly Reward'
}

export const Rarities = {
  Common: 'Common',
  Rare: 'Rare',
  Epic: 'Epic',
  Legendary: 'Legendary',
  LegendaryUnique: 'Legendary - Unique'
}

export const MetaRaces = {
  Mer: [
    'Dark Elf',
    'High Elf',
    'Wood Elf',
    'Orc',
    'Dwemer',
    'Falmer',
    'Ayleid'
  ],
  'Playable Race': [
    'Dark Elf',
    'High Elf',
    'Wood Elf',
    'Orc',
    'Redguard',
    'Breton',
    'Imperial',
    'Nord',
    'Khajiit',
    'Argonian'
  ],
  Animal: [
    'Beast',
    'Fish',
    'Mammoth',
    'Mudcrab',
    'Reptile',
    'Skeever',
    'Spider',
    'Wolf'
  ],
  Undead: ['Mummy', 'Skeleton', 'Spirit', 'Vampire']
}

export const Races = {
  Argonian: 'Argonian',
  Ayleid: 'Ayleid',
  Automaton: 'Automaton',
  Beast: 'Beast',
  Breton: 'Breton',
  Centaur: 'Centaur',
  Chaurus: 'Chaurus',
  Creature: 'Ash Creature',
  Daedra: 'Daedra',
  Defense: 'Defense',
  Dragon: 'Dragon',
  Dreugh: 'Dreugh',
  Dwemer: 'Dwemer',
  'Dark Elf': 'Dark Elf',
  'High Elf': 'High Elf',
  'Wood Elf': 'Wood Elf',
  Elytra: 'Elytra',
  Fabricant: 'Fabricant',
  Factotum: 'Factotum',
  Falmer: 'Falmer',
  Fish: 'Fish',
  Giant: 'Giant',
  Goblin: 'Goblin',
  God: 'God',
  Grummite: 'Grummite',
  Harpy: 'Harpy',
  Imp: 'Imp',
  Imperial: 'Imperial',
  Khajiit: 'Khajiit',
  Kwama: 'Kwama',
  Lurcher: 'Lurcher',
  Mammoth: 'Mammoth',
  Mantikora: 'Mantikora',
  Minotaur: 'Minotaur',
  Mudcrab: 'Mudcrab',
  Mummy: 'Mummy',
  Nereid: 'Nereid',
  Netch: 'Netch',
  Nord: 'Nord',
  Ogre: 'Ogre',
  Orc: 'Orc',
  Reachman: 'Reachman',
  Redguard: 'Redguard',
  Reptile: 'Reptile',
  Skeever: 'Skeever',
  Skeleton: 'Skeleton',
  Spider: 'Spider',
  Spirit: 'Spirit',
  Spriggan: 'Spriggan',
  Troll: 'Troll',
  Vampire: 'Vampire',
  Wamasu: 'Wamasu',
  Werewolf: 'Werewolf',
  Wolf: 'Wolf',
  Wraith: 'Wraith'
}

export const CardTypes = {
  Action: 'Action',
  Item: 'Item',
  Support: 'Support',
  Creature: 'Creature'
}
